# This workflow will install Python dependencies, run tests with a single version of Python

name: Sanity Suite

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  sanity:
    name: Perform Sanity
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install required dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install --with=test

    - name: Perform Sanity Tests
      run: |
        poetry run pytest
